; PlatformIO Project Configuration
; Open StreamDeck - ESP32 BLE+USB JSON StreamDeck
; Board: ESP32 DOIT DevKit V1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM4
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=1

lib_deps =
    madhephaestus/ESP32Encoder@^0.10.1
    fastled/FastLED@^3.6.0
    bblanchon/ArduinoJson@^6.21.0
